spring:
  application:
    name: icpr
  datasource:
    url: jdbc:mysql://localhost:3306/icpr
    username: root
    password: "031231"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        boot:
          allow_jdbc_metadata_access: false
